#  Imagem base
FROM python:3.12.9-slim

# Definindo variáveis de ambiente
ENV DEBIAN_FRONTEND=noninteractive

# Instalação de dependências do sistema
RUN apt-get update && \
    apt-get install -y curl gnupg build-essential && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Dir do projeto
WORKDIR /app
COPY . .

# Instala dependências Node.js E depois as Python
RUN npm install && npm run install-dependencies

# Expondo a porta 8000
EXPOSE 8000

# Comando para iniciar o servidor
CMD ["npm", "run", "start"]
